apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default

  sources:
    - repoURL: https://kiali.org/helm-charts
      chart: kiali-server
      targetRevision: 1.78.0
      helm:
        valueFiles:
          - $values/manifests/kiali/kiali-values.yaml
    - repoURL: https://github.com/ryokushaka/kabu-agent-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
