apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kabu-backend
  namespace: kabu-agent
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: api.DOMAIN_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kabu-backend
                port:
                  number: 8000
  tls:
    - hosts:
        - api.DOMAIN_NAME
      secretName: kabu-backend-tls
